## Path Configuration
export PATH="$PATH:$HOME/bin"
export PATH="$PATH:/usr/local/bin"
export PATH="$PATH:$HOME/.local/bin"

export TERM=vte-256color

## Editor
export EDITOR='nvim'
export VISUAL='nvim'
export FPP_EDITOR='nvim'

export FZF_DEFAULT_OPTS="--history=$HOME/.fzf_history"
export KEYTIMEOUT=1
