# Uncomment this and comment at bottom to profile zsh load time
# zmodload zsh/zprof

# Download Znap, if it's not there yet.
[[ -f ~/dotfiles/zsh/snap/zsh-snap/znap.zsh ]] ||
    git clone --depth 1 -- \
        https://github.com/joshuaMarple/zsh-snap.git ~/dotfiles/zsh/snap/zsh-snap

# source spaceship before starting prompt to speed it up even more
source ~/dotfiles/zsh/snap/zsh-snap/znap.zsh
# source ~/dotfiles/zsh/spaceship.zsh
PROMPT="%F{#50a14f}%(!.#.) %f"
RPROMPT="%(?..✘) %2~"
setopt TRANSIENT_RPROMPT
precmd() { print "" }
ZVM_CURSOR_STYLE_ENABLED=true
ZVM_LAZY_KEYBINDINGS=false
ZVM_INIT_MODE=sourcing

# znap prompt joshuaMarple/spaceship-prompt

znap source Aloxaf/fzf-tab
znap source zsh-users/zsh-autosuggestions
znap source mafredri/zsh-async
znap source seletskiy/zsh-fuzzy-search-and-edit
znap source MenkeTechnologies/zsh-expand
# znap source Valiev/almostontop
znap source jeffreytse/zsh-vi-mode

### Prompt
# spaceship_vi_mode_enable # https://github.com/spaceship-prompt/spaceship-prompt/issues/157

## Zsh Core Settings
bindkey -v

# Its really annoying when zsh tries to match * for files
setopt +o nomatch

### History settings
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_IGNORE_ALL_DUPS  # do not put duplicated command into history list
setopt HIST_SAVE_NO_DUPS  # do not save duplicated command
setopt HIST_REDUCE_BLANKS  # remove unnecessary blanks
setopt INC_APPEND_HISTORY_TIME  # append command to history file immediately after execution
setopt EXTENDED_HISTORY  # record command start time

# Keybinding to edit command line
autoload -z edit-command-line 
zle -N edit-command-line
bindkey "^v" edit-command-line

# Autojump
# https://duganchen.ca/the-simplest-autojump-implementation-for-zsh/
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs
zstyle ':chpwd:*' recent-dirs-default yes
zstyle ':completion:*' recent-dirs-insert always
alias j=cdr
setopt complete_in_word
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'

source ~/.bash_aliases

bindkey '^ ' autosuggest-execute

### Configure ZSH
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="bg=bold,underline"
ZSH_AUTOSUGGEST_USE_ASYNC=true

bindkey '^P' fuzzy-search-and-edit

stty -ixon
bindkey '^q' push-line-or-edit

# https://github.com/spaceship-prompt/spaceship-prompt/issues/91
bindkey "^?" backward-delete-char

eval "$(zoxide init zsh)"

export BAT_THEME="ansi-light"

source ~/dotfiles/zsh/scripts/*

strlen () {
    FOO=$1
    local zero='%([BSUbfksu]|([FB]|){*})'
    LEN=${#${(S%%)FOO//$~zero/}}
    echo $LEN
}

# show right prompt with date ONLY when command is executed
preexec () {
    DATE=$( date +"[%H:%M:%S]" )
    local len_right=$( strlen "$DATE" )
    len_right=$(( $len_right+1 ))
    local right_start=$(($COLUMNS - $len_right))

    local len_cmd=$( strlen "$@" )
    local len_prompt=$(strlen "$PROMPT" )
    local len_left=$(($len_cmd+$len_prompt))

    RDATE="\033[${right_start}C ${DATE}"

    # if [ $len_left -lt $right_start ]; then
        # command does not overwrite right prompt
        # ok to move up one line
        echo -e "\033[1A${RDATE}"
    # else
    #     echo -e "${RDATE}"
    # fi

}

# zprof
