# Uncomment this and comment at bottom to profile zsh load time
# zmodload zsh/zprof

## Zsh Core Settings
bindkey -v

# Its really annoying when zsh tries to match * for files
setopt +o nomatch

### History settings
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_IGNORE_ALL_DUPS  # do not put duplicated command into history list
setopt HIST_SAVE_NO_DUPS  # do not save duplicated command
setopt HIST_REDUCE_BLANKS  # remove unnecessary blanks
setopt INC_APPEND_HISTORY_TIME  # append command to history file immediately after execution
setopt EXTENDED_HISTORY  # record command start time

# Keybinding to edit command line
autoload -z edit-command-line 
zle -N edit-command-line
bindkey "^v" edit-command-line

source ~/.bash_aliases

## Plugin Configuration
### Compinit loading
skip_global_compinit=1
autoload -Uz compinit
compinit -C
source ~/.zsh_plugins.sh
compinit

bindkey '^ ' autosuggest-execute

### Configure ZSH
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="bg=bold,underline"
ZSH_AUTOSUGGEST_USE_ASYNC=true

bindkey '^P' fuzzy-search-and-edit

bindkey '^O' repl-set

eval "$(zoxide init zsh)"

export BAT_THEME="ansi-light"

source ~/dotfiles/zsh/scripts/*

### Prompt
source ~/dotfiles/zsh/spaceship.zsh

# zprof
